update config

diff --git a/.tugboat/config.yml b/.tugboat/config.yml
--- a/.tugboat/config.yml
+++ b/.tugboat/config.yml
@@ -44,8 +44,46 @@ services:
         # repository, change that here. This example links /web to the docroot
         [ -d "${DOCROOT}" ] || ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
 
+        echo '......'
+        echo '......'
+        echo '......'
+
+        echo 'Hello'
+
+        echo ${TUGBOAT_ROOT}/web
+        echo ${DOCROOT}
+
         docker-php-ext-install opcache
         a2enmod headers rewrite
+
+        echo '......'
+        echo '......'
+        echo '......'
+
+        # WebP
+        echo '......'
+        echo 'Install apt......'
+        apt-get install -y libwebp-dev libwebp6 webp libmagickwand-dev
+        docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
+        docker-php-ext-install gd
+
+        echo '......'
+        echo '......'
+        echo '......'
+        echo 'Configure GD ......'
+
+        # Configure GD
+        apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
+        docker-php-ext-configure gd --with-jpeg --with-freetype && docker-php-ext-install gd
+
+        echo '......'
+        echo '......'
+        echo '......'
+        echo 'Install drush launcher ......'
+
+        # Install drush-launcher, if desired.
+        wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
+        chmod +x /usr/local/bin/drush
 
       # Commands that import files, databases,  or other assets. When an
       # existing preview is refreshed, the build workflow starts here,
@@ -60,9 +98,9 @@ services:
         # https://architecture.lullabot.com/adr/20210729-stage-file-proxy/
 
         # Set up permissions for the files directories.
-        chgrp -R www-data "${DOCROOT}/sites/default/files"
-        chmod -R g+w "${DOCROOT}/sites/default/files"
-        chmod 2775 "${DOCROOT}/sites/default/files"
+        chgrp -R www-data "${TUGBOAT_ROOT}/web/sites/default/files"
+        chmod -R g+w "${TUGBOAT_ROOT}/web/sites/default/files"
+        chmod 2775 "${TUGBOAT_ROOT}/web/sites/default/files"
 
         composer install
 
@@ -73,6 +111,15 @@ services:
         # as document at <LINK> and instead run:
         # vendor/bin/task <provider>:fetch-db
         # vendor/bin/task drupal:import-db
+
+        # Install
+        echo "Install drush"
+        # drush site:install
+        drush site:install
+      #        if [[ "drush site:install == "NULL" ]]; then
+      #          echo -e "FATAL ERROR: Not installed"
+      #          exit 1
+      #        fi
 
       # Commands that build the site. This is where you would add things
       # like feature reverts or any other drush commands required to
