install site test

diff --git a/.tugboat/config.yml b/.tugboat/config.yml
--- a/.tugboat/config.yml
+++ b/.tugboat/config.yml
@@ -116,10 +116,10 @@ services:
         echo "Install drush"
         # drush site:install
         drush site:install
-        if [[ "drush site:install == "NULL" ]]; then
-          echo -e "FATAL ERROR: Not installed"
-          exit 1
-        fi
+#        if [[ "drush site:install == "NULL" ]]; then
+#          echo -e "FATAL ERROR: Not installed"
+#          exit 1
+#        fi
 
       # Commands that build the site. This is where you would add things
       # like feature reverts or any other drush commands required to
